# Generated by Django 6.0.3 on 2026-07-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0004_expensetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='monthly_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Месячный лимит (руб.)'),
        ),
    ]
